version: "3.9"
services:
  cassandra:
    image: cassandra:5.0
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_NUM_TOKENS=1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=256M
    volumes:
      - cass_data:/var/lib/cassandra
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2g

volumes:
  cass_data: